### PR TITLE
[SCR-256] [SCR-1] feat: Use v2 API

### PR DESCRIPTION
**Pull request by KillianCourvoisier**
Website change their API to upgrade to v2, we're now fetching it to retrieve data

### CODE REVIEW

**Comment by samlach2222** [comment]
This PR was written in March, is there a reason why it's not being accepted?

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222, yes it's been a while indeed, as you can see in the code, this PR uses the demo API. We're currently missing informations (like a real account) to finalize this PR.

Actually, wild guess but i assume you would use this konnector if it was fixed, right ?
If so, it may help us :)

**Comment by samlach2222** [comment]
Yes, if the modification was available on my Cozy I would use it. Currently uploading my payslips to Cozy doesn't work with the konnector and I don't know of any way to install one's own konnectors on an instance hosted directly with Cozy.

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222 ! :tophat: 
You only could install your own version of a konnector on a cozy running on local stack. You cannot if your using your cozy like the majority of our users (online, via browser or the Cozy app).

But, if you are planning to use it, can I ask you to take a look for us in the network tab of a browser console after login into your account ?
Just go to edoc website , press F12 to open the console, and do your login as usual, then check the requests.

For example starting with the base url [here, L27](https://github.com/konnectors/edoc/blob/fix/appV2/src/index.js#L27) 
We assume it might be something like `https://v2-prod.edocperso.fr` or `https://v2.edocperso.fr` but no way to be sure as we just have a demo account ...
As you can see, the login url is slightly different from the navigation (post-login) urls, when you request to show documents or/and try to download them etc ..

Having hints regarding this will surely help us !
You can also send  full requests example if you like so, specificaly for the documents request, but please **do not forget to anonymize your data** (obviously, but better safe than sorry !  :pray: )

If you manage to find the prod equivalent of their demo urls, we might be able to resolve the issue and finally release a working version of this konnector :)

**Comment by samlach2222** [comment]
As I can see, the url for identify is : `api.stonly.com`.
the url for edocPerso requests is : `https://v2-app.edocperso.fr/` for example : `https://v2-app.edocperso.fr/folders/details`

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222 , thank you for your response !

I'll take a look a this as soon as I have some availabilities to do so, and i'll make sure you will know about when it will be done. This could really help us 🙏

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222 🎩 

I have installed a modified version on your cozy. It seems to work on other users account but we need confirmation. Can you please launch your konnector to make a test run ? 
Tell me about your experience afterward, I'll go check the logs on my side. If you are telling me it is ok for you, it will be release, if not we'll continue working together to find the problem 👍

**Comment by samlach2222** [comment]
Hi, it works in my Cozy.
uploading my payslips to Cozy works

**Comment by KillianCourvoisier** [comment]
Wonderful ! Lemme check the logs anyway, but release incoming 👌 
Thank you very much for the hints 🙏

**Comment by KillianCourvoisier** [comment]
I'll install you back the stable version so until the new version is fully released, running it wont work as expected, so don't worry 👍

**Review by doubleface — APPROVED** [review]

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222 , i hope this message find you well.

Some users are complaining about this konnector. As you helped me on fixing it, I was wondering if you could check on your side.

Apparently, files from 2024 (mostly payslips) are not downloaded despite finishing on success. 

Are you impacted by this ? have you noticed anything special for 2024 files on your side ?
Maybe they are presented differently or something like that, if you find something, it would be nice of you to tell me.

Thanks in advance, have a good day mate, cheers.

**Comment by samlach2222** [comment]
Hello @KillianCourvoisier, I only have documents from 2024 so I can't compare with other years. 
Since 1 or 2 month, the eDocPerso connector don't works (sync error) in my cozy.

When you had installed the modified version in my cozy, I got all my documents (from 2024) but, because of the sync error, I don't get new documents.

**Comment by KillianCourvoisier** [comment]
Hello @samlach2222 thanks for the feedback, apparently the konnectors is still functionning globaly but still gets no documents back. I'll take a look after my next subject.

Thank you again, have a good day 👍

**Pull request merged**
